namespace:
  name: demo
 
image:
  repository: nginx
  tag: alpine

replicaCount: 3

pullpolicy: IfNotPresent

resources:
  cpu: 50m
  memory: 256Mi

service:
  type: ClusterIP
  port: 8111

configmap:
  version:
    name: version
    value: alpine
