namespace:
  name: pythonking-prod
 
image:
  repository: nginx
  tag: 1.17.0

replicaCount: 2

resources:
  cpu: 70m
  memory: 256Mi

service:
  port: 80

configmap:
  version:
    name: version
    value: 1.17.0
