apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    tag: pyapp
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Values.name }}
    tag: pyapp
  type: ClusterIP
